# Generated by Django 3.1.7 on 2021-02-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productadvert',
            name='advert_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
