# Generated by Django 3.1.7 on 2021-02-22 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210222_0136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='review_percentage',
            new_name='rating',
        ),
    ]
