# Generated by Django 3.1.7 on 2021-03-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FASHION_BEAUTY', 'Fashion & Beauty'), ('KIDS_CLOTHES', 'Kids & Babies Clothes'), ('MEN_WOMEN_CLOTHES', 'Men & Women Clothes'), ('GADGETS_ACCESSORIES', 'Gadgets & Accessories'), ('ELECTRONICS_ACCESSORIES', 'Electronics & Accessories')], max_length=100, null=True),
        ),
    ]
