# Generated by Django 3.1.7 on 2021-03-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210301_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='productadvert',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='productadvert',
            name='sub_duration',
            field=models.CharField(choices=[('DAILY', 'One(1) Day - ₦1,000'), ('MONTHLY', 'One(1) Month - ₦25,000'), ('YEARLY', 'One(1) Year - ₦300,000')], default='DAILY', max_length=100),
        ),
    ]
