# Generated by Django 3.1.7 on 2021-03-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210302_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productadvert',
            name='advert_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productadvert',
            name='advert_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
