# Generated by Django 3.1.7 on 2021-02-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='permanent_address',
        ),
        migrations.AddField(
            model_name='profile',
            name='shipping_address',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
