# Generated by Django 3.1.7 on 2021-02-24 20:19

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210224_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
