# Generated by Django 3.1.7 on 2021-03-01 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20210224_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=400, null=True)),
                ('first_name', models.CharField(max_length=400, null=True)),
                ('last_name', models.CharField(max_length=400, null=True)),
                ('bank_name', models.CharField(max_length=400, null=True)),
                ('bank_number', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact', models.CharField(max_length=20, null=True)),
                ('alternate_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(choices=[('FASHION_BEAUTY', 'Fashion & Beauty'), ('KIDS_CLOTHES', 'Kids & Babies Clothes'), ('MEN_WOMEN_CLOTHES', 'Men & Women Clothes'), ('GADGETS_ACCESSORIES', 'Gadgets & Accessories'), ('ELECTRONICS_ACCESSORIES', 'Electronics & Accessories')], max_length=400, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
