# Generated by Django 3.1.7 on 2021-02-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_uid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
