# Generated by Django 3.1.7 on 2021-03-01 15:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210301_1441'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PendingOrders',
            new_name='PendingOrder',
        ),
    ]
